"""baseline_schema

Revision ID: 0001
Revises: 
Create Date: 2026-04-12 00:45:28.206498
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chd_metadata',
    sa.Column('chd_path', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('mtime', sa.Float(), nullable=True),
    sa.Column('cached_at', sa.String(), nullable=True),
    sa.Column('disc_id_checked', sa.Boolean(), nullable=False),
    sa.Column('disc_id_checked_mtime', sa.Float(), nullable=True),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('chd_path')
    )
    op.create_table('dat_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_sync_tag', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.String(), nullable=True),
    sa.Column('last_sync_files', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dats',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('imported_at', sa.String(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifications',
    sa.Column('chd_path', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=True),
    sa.Column('verified_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('chd_path')
    )
    op.create_table('dat_hashes',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('hash_type', sa.String(length=8), nullable=False),
    sa.Column('dat_id', sa.String(length=16), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('rom_name', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dat_id'], ['dats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hash', 'hash_type')
    )
    with op.batch_alter_table('dat_hashes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dat_hashes_dat_id'), ['dat_id'], unique=False)

    op.create_table('dat_matches',
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('dat_id', sa.String(length=16), nullable=True),
    sa.Column('game_name', sa.String(), nullable=True),
    sa.Column('rom_name', sa.String(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dat_id'], ['dats.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('path')
    )
    with op.batch_alter_table('dat_matches', schema=None) as batch_op:
        batch_op.create_index('ix_dat_matches_dat_id', ['dat_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrade migrations are not supported in this project — forward-only.
    raise NotImplementedError("downgrade not supported")
